#!/bin/sh

# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged,
# for example tap="tap0 tap1 tap2".
tap="tap0"

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
eth="eth2"
eth_ip="10.0.0.10"
eth_netmask="255.255.255.0"
eth_broadcast="10.0.0.255"
#eth_gateway="192.168.5.1"

/sbin/ifconfig $br down
/sbin/brctl delbr $br

for t in $tap; do
/usr/sbin/openvpn --rmtun --dev $t
done

/sbin/ifconfig $eth $eth_ip netmask $eth_netmask broadcast $eth_broadcast

#/sbin/route add default gw $eth_gateway
