#!/bin/bash

# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged,
# for example tap="tap0 tap1 tap2".
tap="tap0"

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
eth=$2
eth_ip=$3
eth_netmask="255.255.255.0"
eth_broadcast="10.0.0.255"

start() {
	for t in $tap; do
		/usr/sbin/openvpn --mktun --dev $t
	done

	/sbin/brctl addbr $br
	/sbin/brctl addif $br $eth

	for t in $tap; do
		/sbin/brctl addif $br $t
	done

	for t in $tap; do
		/sbin/ifconfig $t 0.0.0.0 promisc up
	done

	/sbin/ifconfig $eth 0.0.0.0 promisc up

	/sbin/ifconfig $br $eth_ip netmask $eth_netmask broadcast $eth_broadcast
}

stop() {
	/sbin/ifconfig $br down
	/sbin/brctl delbr $br

	for t in $tap; do
	/usr/sbin/openvpn --rmtun --dev $t
	done

	/sbin/ifconfig $eth $eth_ip netmask $eth_netmask broadcast $eth_broadcast
}

case "$1" in 
	start)   start ;;
	stop)    stop ;;
	*) echo "usage: $0 start|stop" >&2
	exit 1
	;;
esac
